2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Configure stats pid to 192
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Loading settings from /home/studio-lab-user/.config/wandb/settings
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Loading settings from /home/studio-lab-user/Generative_Models_for_CERN_Fast_Simulations/notebooks/gan_proton_15_2312/wandb/settings
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_init.py:_log_setup():506] Logging user logs to /home/studio-lab-user/Generative_Models_for_CERN_Fast_Simulations/notebooks/gan_proton_15_2312/wandb/run-20230327_120435-5j4nb3tu/logs/debug.log
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_init.py:_log_setup():507] Logging internal logs to /home/studio-lab-user/Generative_Models_for_CERN_Fast_Simulations/notebooks/gan_proton_15_2312/wandb/run-20230327_120435-5j4nb3tu/logs/debug-internal.log
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd4bc707a30>
2023-03-27 12:04:35,476 INFO    MainThread:192 [wandb_init.py:init():546] calling init triggers
2023-03-27 12:04:35,477 INFO    MainThread:192 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'Model': 'gan', 'dataset': 'proton_data', 'epochs': 200, 'Date': '27_03_2023_12_04', 'Proton_min': 15.0, 'Proton_max': 2133.0, 'Experiment_dir_name': 'experiments/gan_15_2133_27_03_2023_12_04'}
2023-03-27 12:04:35,477 INFO    MainThread:192 [wandb_init.py:init():568] re-initializing run, found existing run on stack: ix3xb2ep
2023-03-27 12:04:35,478 INFO    MainThread:192 [wandb_run.py:_finish():1854] finishing run generative-models-cern/Generative Models for CERN Fast Simulations/ix3xb2ep
2023-03-27 12:04:35,478 INFO    MainThread:192 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-27 12:04:35,478 INFO    MainThread:192 [wandb_run.py:_restore():2066] restore
2023-03-27 12:04:35,478 INFO    MainThread:192 [wandb_run.py:_restore():2072] restore done
2023-03-27 12:04:40,850 INFO    MainThread:192 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-03-27 12:04:40,850 INFO    MainThread:192 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-03-27 12:04:40,856 INFO    MainThread:192 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-03-27 12:04:40,861 INFO    MainThread:192 [wandb_init.py:init():602] starting backend
2023-03-27 12:04:40,861 INFO    MainThread:192 [wandb_init.py:init():606] setting up manager
2023-03-27 12:04:40,863 INFO    MainThread:192 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-27 12:04:40,864 INFO    MainThread:192 [wandb_init.py:init():613] backend started and connected
2023-03-27 12:04:40,877 INFO    MainThread:192 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-03-27 12:04:40,878 INFO    MainThread:192 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-27 12:04:40,878 INFO    MainThread:192 [wandb_init.py:init():701] updated telemetry
2023-03-27 12:04:40,997 INFO    MainThread:192 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-27 12:04:42,126 INFO    MainThread:192 [wandb_run.py:_on_init():2133] communicating current version
2023-03-27 12:04:42,210 INFO    MainThread:192 [wandb_run.py:_on_init():2142] got version response 
2023-03-27 12:04:42,210 INFO    MainThread:192 [wandb_init.py:init():789] starting run threads in backend
2023-03-27 12:04:44,739 INFO    MainThread:192 [wandb_run.py:_console_start():2114] atexit reg
2023-03-27 12:04:44,739 INFO    MainThread:192 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-27 12:04:44,739 INFO    MainThread:192 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-27 12:04:44,740 INFO    MainThread:192 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-27 12:04:44,740 INFO    MainThread:192 [wandb_init.py:init():831] run started, returning control to user process
2023-03-27 12:04:44,744 INFO    MainThread:192 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-27 12:04:44,744 INFO    MainThread:192 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-27 12:04:44,755 INFO    MainThread:192 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-27 12:04:46,016 INFO    MainThread:192 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-27 12:04:46,016 INFO    MainThread:192 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-27 12:04:46,024 INFO    MainThread:192 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-27 12:04:46,220 INFO    MainThread:192 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-27 12:04:46,225 INFO    MainThread:192 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-27 12:04:46,242 INFO    MainThread:192 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-27 12:04:46,562 INFO    MainThread:192 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-27 12:04:46,562 INFO    MainThread:192 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-27 12:04:46,582 INFO    MainThread:192 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-27 12:04:46,585 INFO    MainThread:192 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-27 12:04:46,585 INFO    MainThread:192 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-27 12:04:46,590 INFO    MainThread:192 [wandb_init.py:_resume_backend():422] resuming backend
